### ISSUE TITLE
Animation Event Listeners

### ISSUE THREAD

**Issue by gyochum** [developertown/react-lottie-hook#7]
Hi,  I would like to know when an animation has completed, so I am creating a list of EventListeners and passing them into  useLottie()...

`const listeners: EventListener[] = [{
        eventName: "error",
        callback: (data) => console.log("ANIMATION ERROR!  ", data)
    }, {
        eventName: "complete",
        callback: (data) => console.log("ANIMATION COMPLETE!  ", data)
    }];

const [lottieRef, {isStopped, isPaused}, controls] = useLottie({
        renderer: "svg",
        rendererSettings: {
             preserveAspectRatio: "xMidYMid slice"
        },        
        loop: false,
        autoplay: autoplay,
        eventListeners: listeners,
        animationData: data
    });
`
However when I render the Lottie component and the animations plays, none of the events are triggered.  Is there something I am missing here?

**Comment by hanorine** [comment]
Hi @gyochum,

Thank you for finding interest in `react-lottie-hook` and bringing your issue to my attention.

I've looked into your issue and discovered that one of the registerListeners was placed after setAnimation. I worked on a solution and hope to get it up and in your hands as soon as possible.

I apologize for any inconveniences.

**Comment by gyochum** [comment]
@JaysQubeXon I just installed 0.1.0 and it works really well - thanks so much for the quick response!

**Comment by hanorine** [comment]
You're quite welcome @gyochum .
