### ISSUE TITLE
Direction of Animation

### ISSUE THREAD

**Issue by ahwelgemoed** [developertown/react-lottie-hook#9]
Hi

I like the package and I am using it for a project currently.

I needed the ability to change the animation direction, I saw that it was declared in the Types, but never coded in.

I forked and added it in, It's a simple and small fix.

I will submit a PR.

I would also like to get the current Direction of the animation, but could not find a quick way to do it, when it gets more pressing issue I might look at it again if you have not implemented it by then.

Thanks for the great work!

**Comment by hanorine** [comment]
Hi @ahwelgemoed,

Thanks you for opening the PR. I saw it and hopefully will be able to examine it closer later today if not tomorrow.
